// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.MagPerception
{
    static partial class BuildInfo
    {
		public const int Epoch = 1708744760;
		public const string GitCommit = "18e9a03a7fa240597d75355b8f1defcdb5cbf3c5";
    }
}