// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.MagPerception
{
    static partial class BuildInfo
    {
		public const int Epoch = 1715183440;
		public const string GitCommit = "24e6d15aeb6db164b268ff93c34540be1729ddbc";
    }
}