// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.MagPerception
{
    static partial class BuildInfo
    {
		public const int Epoch = 1707451384;
		public const string GitCommit = "743077e566916fa6a0123027cddaa8fc539a85b0";
    }
}